### ISSUE TITLE
adding openpyxl to the requirement file

### ISSUE THREAD

**Issue by maboualidev** [microsoft/BatteryML#18]
`openpyxl` needs to be added to the requirements, otherwise, `convert_data_format()` will fail on `CALCE` data set:

```
Processing dataset CALCE:  88%|███████████████████████████████████████████████████████████████████████████████▋           | 7/8 [34:08<04:52, 292.61s/it]
Traceback (most recent call last):                                                                                                                       
  File "/Users/moeabo/miniforge3/envs/battery_ml/lib/python3.10/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/moeabo/miniforge3/envs/battery_ml/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'
```

**Comment by fingertap** [comment]
Yes, thanks for your feedback!

**Comment by fingertap** [comment]
This is handled in #19 . Closing.

**Comment by HasanTheSyrian** [comment]
XGBoost is also not added I had to manually install it.

**Comment by hilinxinhui** [comment]
also, 'requests' is also not added I had to manually install it:
![90167d65-4ceb-41f6-aeec-f438256b7b4d](https://github.com/microsoft/BatteryML/assets/72953081/87d22948-a3a2-41bf-ad4f-056a827c8785)
