### ISSUE TITLE
feature_transformation error

### ISSUE THREAD

**Issue by Kashif-Raza6** [microsoft/BatteryML#54]
When I am trying to run the transformer model it throws the feature transformation error;

```
batteryml run configs\baselines\nn_models\transformer\hust.yaml --workspace .\workspace\test --train --eval
```

Error;

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mbml\Scripts\batteryml.exe\__main__.py", line 7, in <module>
  File "mbml\Lib\site-packages\bin\batteryml.py", line 84, in main
    args.func(args)
  File "mbml\Lib\site-packages\bin\batteryml.py", line 118, in run
    pipeline = Pipeline(args.config, args.workspace)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mbml\Lib\site-packages\batteryml\pipeline.py", line 28, in __init__
    self.config = load_config(config_path, workspace)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mbml\Lib\site-packages\batteryml\pipeline.py", line 157, in load_config
    configs = import_config(config_path, config_fields)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mbml\Lib\site-packages\batteryml\utils\config.py", line 35, in import_config
    raise ValueError(f"Missing expected config fields: {missing_fields}")
ValueError: Missing expected config fields: ['feature_transformation']
```

**Comment by Kashif-Raza6** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/microsoft/BatteryML/issues/54?shareId=15c1201d-0e7b-4a03-a49d-e89fb9eee68c) saved by @Kashif-Raza6 using Copilot Workspace v0.27

**Comment by agiamason** [comment]
Hi @Kashif-Raza6 , we've fixed this bug, could you re-pull the newest main branch of the BatteryML?
